app_config: test
not_in_schema: true

network:
  server:
    host: "127.0.0.1"

test:
  req_bool_val: true
  req_bool_val_or_none: None
  req_int_val: 176
  req_int_list_val: [12, 13, 14, 15, 16]
  req_float_val: 1.55
  req_str_val: test string
  req_enum_val: val1
  req_int_val_none_union: None
  req_tuple_int: (12)
  req_tuple_int_float: (12, 11.5)
  req_tuple_int_float_none: (12, None)
